services:
  spring-app:
    image: ${ECR_REGISTRY}/cp_main_be:latest
    container_name: spring-app-container
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      # Firebase 서비스 계정 키 파일을 컨테이너 내부로 마운트
      - ./napulnapul-d9572-firebase-adminsdk-fbsvc-0a2757f074.json:/app/napulnapul-d9572-firebase-adminsdk-fbsvc-0a2757f074.json:ro
    restart: always
