# docker-compose.yml
services:
  spring-app:
    image: ${ECR_REGISTRY}/cp_main_be:latest
    container_name: spring-app-container
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    # volumes 섹션은 완전히 삭제
    restart: always