server:
  forward-headers-strategy: framework

spring:
  profiles:
    active: local
  application:
    name: CP_Main_BE
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    debug: true
  config:
    import: "optional:dotenv:"

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-milliseconds: 3600000
  refresh-token-expiration-milliseconds: 604800000

cloudflare:
  r2:
    endpoint: ${R2_ENDPOINT}
    bucket: ${R2_BUCKET}
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}

fastapi:
  server:
    url: ${FASTAPI_URL}

logging:
  level:
    org:
      springframework:
        security: TRACE

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    debug: false

springdoc:
  swagger-ui:
    servers:
      - url: https://api.napulnapul.com
        description: Production Server